### ISSUE TITLE
can you provide end user friendly installation documentation?

### ISSUE THREAD

**Issue by lsmith77** [inab/wiktionary-term-fetcher#1]

**Comment by jmfernandez** [comment]
Dear @lsmith77 , the package is also available at pypi (see https://pypi.org/project/wiktionary-term-fetcher/). Next commands are an example about how to create a Python virtual environment and install there the package:

```bash
python3 -mvenv wiktionary-install-dir
source wiktionary-install-dir/bin/activate
pip install --upgrade pip wheel
pip install wiktionary-term-fetcher
```

Within that environment next commands should work

```bash
wiktionary-fetcher --help
wiktionary-fetcher --lang en --terms verbs english_verbs.txt
```

If you were meaning how to use it in a programmatic way, I still have to provide an example.

Hope this helps!

**Comment by lsmith77** [comment]
indeed it did!
